### ISSUE TITLE
Compilation error sprintf is deprecated

### ISSUE THREAD

**Issue by chabaneguillaume** [sainteos/tmxparser#86]
Hello, Got this trying to build on osx 13.3

/Documents/GitHub/tmxparser/src/TmxColor.cpp:98:14: error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]
        std::sprintf(strRep, "#%.8x", color);
             ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk/usr/include/sys/cdefs.h:215:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
1 error generated.
make[2]: *** [CMakeFiles/tmxparser.dir/src/TmxColor.cpp.o] Error 1
make[1]: *** [CMakeFiles/tmxparser.dir/all] Error 2
make: *** [all] Error 2
